"""add_updated_at_to_users

Revision ID: 45ba6d327ae0
Revises: a062264c1652
Create Date: 2026-03-09 09:40:33.007076

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "45ba6d327ae0"
down_revision = "a062264c1652"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
            comment="Last update timestamp",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###
