"""add missing DB fields

Revision ID: a062264c1652
Revises: add_audit_logs_table
Create Date: 2026-03-08 11:38:19.376854

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a062264c1652"
down_revision = "add_audit_logs_table"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create enums if they don't exist
    from sqlalchemy.dialects import postgresql

    session_state = postgresql.ENUM(
        "CREATED", "RUNNING", "PAUSED", "STOPPED", "ERROR", name="sessionstate"
    )
    session_state.create(op.get_bind(), checkfirst=True)
    task_status = postgresql.ENUM(
        "PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="taskstatus"
    )
    task_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_keys",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        comment="Expiration timestamp - API keys must have an expiry date",
        existing_comment="Expiration timestamp",
    )
    op.alter_column(
        "audit_logs",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Additional details about the action",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("audit_logs_user_id_fkey"), "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        None, "audit_logs", "users", ["user_id"], ["user_id"], ondelete="SET NULL"
    )
    op.drop_index("ix_refresh_tokens_token_hash", table_name="refresh_tokens")
    op.alter_column(
        "session_data",
        "data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="State data as JSON",
        existing_nullable=False,
    )
    op.alter_column(
        "session_templates",
        "custom_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Default custom configuration overrides",
        existing_nullable=True,
    )
    # op.create_unique_constraint(
    #     "uq_session_templates_user_name", "session_templates", ["user_id", "name"]
    # )
    # op.add_column(
    #     "sessions",
    #     sa.Column(
    #         "full_state", sa.JSON(), nullable=True, comment="Full APGI system state for persistence"
    #     ),
    # )
    op.add_column(
        "sessions",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="Soft delete flag",
        ),
    )
    op.alter_column(
        "sessions",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Session configuration as JSON",
        existing_nullable=False,
    )
    op.alter_column(
        "sessions",
        "state",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("CREATED", "RUNNING", "PAUSED", "STOPPED", "ERROR", name="sessionstate"),
        existing_comment="Current session state",
        postgresql_using="state::sessionstate",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "parameters",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Task parameters as JSON",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="taskstatus"),
        existing_comment="Current task status",
        postgresql_using="status::taskstatus",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "result_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Task results as JSON",
        existing_nullable=True,
    )
    op.add_column(
        "users",
        sa.Column(
            "failed_login_attempts",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Number of consecutive failed login attempts",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "locked_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Account lockout expiration timestamp",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "mfa_secret", sa.String(length=255), nullable=True, comment="TOTP secret for MFA"
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "mfa_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="Whether MFA is enabled",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verification_token",
            sa.String(length=255),
            nullable=True,
            comment="Token for email verification",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verification_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Token expiration",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="Soft delete flag",
        ),
    )
    op.drop_column("users", "updated_at")
    # op.add_column(
    #     "webhook_deliveries",
    #     sa.Column(
    #         "retry_count",
    #         sa.Integer(),
    #         nullable=False,
    #         server_default="3",
    #         comment="Maximum retry attempts",
    #     ),
    # )
    # op.add_column(
    #     "webhook_deliveries",
    #     sa.Column(
    #         "retry_delays",
    #         sa.JSON(),
    #         nullable=False,
    #         server_default="[]",
    #         comment="Retry delay schedule in seconds",
    #     ),
    # )
    op.alter_column(
        "webhook_deliveries",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Webhook payload as JSON",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhook_deliveries",
        "payload",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Webhook payload as JSON",
        existing_nullable=False,
    )
    op.drop_column("webhook_deliveries", "retry_delays")
    op.drop_column("webhook_deliveries", "retry_count")
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Last update timestamp",
        ),
    )
    op.drop_column("users", "is_deleted")
    op.drop_column("users", "email_verification_expires_at")
    op.drop_column("users", "email_verification_token")
    op.drop_column("users", "mfa_enabled")
    op.drop_column("users", "mfa_secret")
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_attempts")
    op.alter_column(
        "tasks",
        "result_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Task results as JSON",
        existing_nullable=True,
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.Enum(
            "PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="taskstatus"
        ),
        type_=sa.VARCHAR(length=20),
        existing_comment="Current task status",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "parameters",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Task parameters as JSON",
        existing_nullable=False,
    )
    op.alter_column(
        "sessions",
        "state",
        existing_type=sa.Enum(
            "CREATED", "RUNNING", "PAUSED", "STOPPED", "ERROR", name="sessionstate"
        ),
        type_=sa.VARCHAR(length=20),
        existing_comment="Current session state",
        existing_nullable=False,
    )
    op.alter_column(
        "sessions",
        "config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Session configuration as JSON",
        existing_nullable=False,
    )
    op.drop_column("sessions", "is_deleted")
    op.drop_column("sessions", "full_state")
    op.drop_constraint("uq_session_templates_user_name", "session_templates", type_="unique")
    op.alter_column(
        "session_templates",
        "custom_config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Default custom configuration overrides",
        existing_nullable=True,
    )
    op.alter_column(
        "session_data",
        "data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="State data as JSON",
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("refresh_tokens_token_hash_key"),
        "refresh_tokens",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("audit_logs_user_id_fkey", "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("audit_logs_user_id_fkey"), "audit_logs", "users", ["user_id"], ["user_id"]
    )
    op.alter_column(
        "audit_logs",
        "details",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Additional details about the action",
        existing_nullable=True,
    )
    op.alter_column(
        "api_keys",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        comment="Expiration timestamp",
        existing_comment="Expiration timestamp - API keys must have an expiry date",
    )
    # ### end Alembic commands ###
