#!/usr/bin/env python3
"""
Generate README.md's identifier block, CITATION.cff, and .zenodo.json from
identifiers.yaml — the single source of truth for APGI's canonical
identifiers (ORCID, OSF, Zenodo DOIs, licences, release state).

Usage:
    python scripts/generate_identifiers.py          # write the generated files
    python scripts/generate_identifiers.py --check  # exit 1 if any file has drifted

Nothing in the generated files should ever be hand-edited — edit
identifiers.yaml and re-run this script instead. The --check mode is wired
into CI so a hand-edit (or a stale generation) fails the build.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
IDENTIFIERS_PATH = REPO_ROOT / "identifiers.yaml"
README_PATH = REPO_ROOT / "README.md"
CITATION_PATH = REPO_ROOT / "CITATION.cff"
ZENODO_PATH = REPO_ROOT / ".zenodo.json"

README_START = (
    "<!-- IDENTIFIERS:START — generated by scripts/generate_identifiers.py, do not hand-edit -->"
)
README_END = "<!-- IDENTIFIERS:END -->"


def load_identifiers() -> dict[str, Any]:
    with open(IDENTIFIERS_PATH, encoding="utf-8") as f:
        data: dict[str, Any] = yaml.safe_load(f)
    return data


def render_readme_block(ids: dict[str, Any]) -> str:
    researcher = ids["researcher"]
    osf = ids["osf"]
    zenodo = ids["zenodo"]
    code = ids["code"]
    web = ids["web"]
    licences = ids["licences"]
    release_state = ids["release_state"]

    repo_rows = "\n".join(
        f"| [`{r['name']}`]({code['organisation']}/{r['name']}) | {r['role']} | "
        f"{'citable' if r['citable'] else 'not yet citable'} |"
        for r in code["repositories"]
    )

    resolves_note = (
        " (unverified — do not cite until confirmed to resolve)"
        if zenodo["resolves"] != "verified"
        else ""
    )

    lines = [
        README_START,
        "### Identifiers",
        "",
        f"- **Researcher (ORCID):** [{researcher['given_names']} {researcher['family_names']}]"
        f"({researcher['orcid_url']}) `{researcher['orcid']}`",
        f"- **OSF preregistration:** [{osf['project_guid']}]({osf['project_url']})"
        + (
            f" &middot; instrument: [{osf['registration_instrument_guid']}]"
            f"({osf['registration_instrument_url']})"
            if osf.get("registration_instrument_guid")
            else ""
        ),
        f"- **Zenodo concept DOI:** [{zenodo['concept_doi']}]({zenodo['concept_doi_url']})"
        f"{resolves_note}",
        f"- **Version DOI:** {zenodo['version_doi'] or '_not yet minted — cut a tagged release_'}",
        f"- **Web:** [{web['site']}]({web['site']}) &middot; "
        f"API: [{web['api']}]({web['api']}) ({web['api_version']})",
        f"- **Licences:** code `{licences['code']}` &middot; docs `{licences['documentation']}` "
        f"&middot; reference dataset `{licences['reference_dataset']}`",
        f"- **Release state:** `{release_state['current']}`",
        "",
        "| Repository | Role | Zenodo |",
        "|---|---|---|",
        repo_rows,
        "",
        README_END,
    ]
    return "\n".join(lines)


def render_readme(ids: dict[str, Any]) -> str:
    """Full README content, with the generated block spliced in."""
    block = render_readme_block(ids)
    web = ids["web"]

    if README_PATH.exists():
        existing = README_PATH.read_text(encoding="utf-8")
        if README_START in existing and README_END in existing:
            before, rest = existing.split(README_START, 1)
            _, after = rest.split(README_END, 1)
            return before + block + after
        # No markers yet — append the block to the existing file.
        return existing.rstrip("\n") + "\n\n" + block + "\n"

    # No README yet — generate a minimal one around the block.
    return (
        "# APGI System API\n\n"
        "REST API for Allostatic Precision-Gated Ignition (APGI) consciousness "
        "modeling and the APGI research pilot: participant consent, behavioural "
        "battery ingestion, scoring, norms, and psychometrics.\n\n"
        f"{block}\n\n"
        "## Documentation\n\n"
        "- [`docs/DEPLOYMENT.md`](docs/DEPLOYMENT.md) — deployment guide\n"
        "- [`docs/REST-API.md`](docs/REST-API.md) — REST API reference\n"
        "- [`docs/CONFIGURATION.md`](docs/CONFIGURATION.md) — configuration reference\n"
        "- [`docs/COMPLIANCE.md`](docs/COMPLIANCE.md) — security & compliance posture\n"
        "- [`docs/THEORY.md`](docs/THEORY.md) — the APGI model\n\n"
        "## Development\n\n"
        "See [`CLAUDE.md`](CLAUDE.md) for local setup, testing, and architecture notes.\n\n"
        f"Interactive docs are served at `{web['api']}/docs` once the API is deployed.\n"
    )


def render_citation_cff(ids: dict[str, Any]) -> str:
    researcher = ids["researcher"]
    zenodo = ids["zenodo"]
    code = ids["code"]
    release_state = ids["release_state"]
    version = release_state.get("model_version") or "0.0.0"
    repo_url = f"{code['organisation']}/apgi-api"

    identifiers_block = f"""identifiers:
  - type: doi
    value: {zenodo['concept_doi']!r}
    description: "Concept DOI (all versions) for the APGI project on Zenodo"
"""
    if zenodo.get("version_doi"):
        identifiers_block += f"""  - type: doi
    value: {zenodo['version_doi']!r}
    description: "Version DOI for this specific release"
"""

    return f"""# Generated by scripts/generate_identifiers.py from identifiers.yaml — do not hand-edit.
cff-version: 1.2.0
message: "If you use this software, please cite it using these metadata."
title: "APGI System API"
abstract: >-
  REST API for Allostatic Precision-Gated Ignition (APGI) consciousness
  modeling: participant consent, behavioural battery ingestion, scoring,
  norms, and psychometrics.
authors:
  - family-names: {researcher['family_names']!r}
    given-names: {researcher['given_names']!r}
    orcid: {researcher['orcid_url']!r}
version: {version!r}
date-released: {ids['last_reviewed']!s}
license: {ids['licences']['code']!r}
repository-code: {repo_url!r}
url: {ids['web']['site']!r}
{identifiers_block}"""


def render_zenodo_json(ids: dict[str, Any]) -> str:
    import json

    researcher = ids["researcher"]
    osf = ids["osf"]

    payload = {
        "title": "APGI System API",
        "description": (
            "REST API for Allostatic Precision-Gated Ignition (APGI) consciousness "
            "modeling: participant consent, behavioural battery ingestion, scoring, "
            "norms, and psychometrics."
        ),
        "creators": [
            {
                "name": f"{researcher['family_names']}, {researcher['given_names']}",
                "orcid": researcher["orcid"],
            }
        ],
        "license": ids["licences"]["code"],
        "upload_type": "software",
        "access_right": "open",
        "keywords": [
            "consciousness",
            "allostasis",
            "precision-weighting",
            "active inference",
            "psychometrics",
            "REST API",
        ],
        "related_identifiers": [
            {
                "identifier": osf["project_url"],
                "relation": "isSupplementTo",
                "resource_type": "dataset",
            }
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def write_or_check(path: Path, content: str, check: bool, diffs: list[str]) -> None:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            diffs.append(str(path.relative_to(REPO_ROOT)))
        return
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write files; exit 1 if generated content diverges from disk.",
    )
    args = parser.parse_args()

    ids = load_identifiers()

    diffs: list[str] = []
    write_or_check(README_PATH, render_readme(ids), args.check, diffs)
    write_or_check(CITATION_PATH, render_citation_cff(ids), args.check, diffs)
    write_or_check(ZENODO_PATH, render_zenodo_json(ids), args.check, diffs)

    if args.check:
        if diffs:
            print(
                "Generated identifier files have drifted from identifiers.yaml:\n  "
                + "\n  ".join(diffs)
                + "\n\nRun `python scripts/generate_identifiers.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("README.md, CITATION.cff, and .zenodo.json match identifiers.yaml.")
        return 0

    print(f"Wrote {README_PATH.name}, {CITATION_PATH.name}, {ZENODO_PATH.name}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
